### ISSUE TITLE
Dealing with other themes

### ISSUE THREAD

**Issue by DolfDevs** [marinaglancy/moodle-tool_courserating#10]
Title: Course rating plugin not appearing in Lambda theme and New Learning  themes

Description:
I would like to report an issue regarding the course rating plugin not being visible when using the Lambda and the New Learning themes in Moodle.

Steps to Reproduce:

Install Moodle 4.1 and 4.3 with the latest Lambda and New Learning  themes .
Navigate to a course page and observe that the course rating plugin is not displayed.

Expected Behavior:
The course rating plugin should be visible and accessible on the course page when using the two themes.

Observed Behavior:
The course rating plugin is not appearing in the Lambda and New Learning  themes, although it functions correctly in the Boost theme.

Additional Information:

No error messages or warnings are displayed.
Please let me know if you require any further information or if there are any specific steps I should take to assist in resolving this issue. Thank you for your attention to this matter.

**Comment by marinaglancy** [comment]
Hello, please provide the links to the themes source code so I can test with them. I did not find them on moodle.org/plugins

Also check if the course rating widget appears in the bottom of the course page. It is possible that these themes  do not contain the #page-header element.

In this case you can adjust the setting
```
CSS selector for parent element
tool_courserating | parentcss
```
that is located in the Site administration>Courses>Course ratings

**Comment by DolfDevs** [comment]
Thank you for your assistance.
 We would like to inform you that the themes we are using, "Lambda - Responsive Moodle Theme" and "New Learning | Premium Moodle Theme," are paid themes. 
You can find these themes on ThemeForest using the following links:

Lambda - Responsive Moodle Theme: (https://themeforest.net/item/lambda-responsive-moodle-theme/9442816)
New Learning | Premium Moodle Theme: (https://themeforest.net/item/new-learning-premium-moodle-theme/20470826)

We have successfully implemented the solution you provided regarding the parent CSS, and it has worked well for us. We appreciate your support in resolving this matter.

**Comment by DolfDevs** [comment]
Thank you for your assistance.
We would like to inform you that the themes we are using, "Lambda - Responsive Moodle Theme" and "New Learning | Premium Moodle Theme," are paid themes.
You can find these themes on ThemeForest using the following links:

Lambda - Responsive Moodle Theme: (https://themeforest.net/item/lambda-responsive-moodle-theme/9442816)
New Learning | Premium Moodle Theme: (https://themeforest.net/item/new-learning-premium-moodle-theme/20470826)

We have successfully implemented the solution you provided regarding the parent CSS, and it has worked well for us. We appreciate your support in resolving this matter.
