### ISSUE TITLE
Issue with plugin compatibility : Stack and Mathjax

### ISSUE THREAD

**Issue by baltaleloko** [marinaglancy/moodle-tool_courserating#2]
Hello,
first of all, thank you for this beautifull plugin ! As users, we were simply dreaming about such a addition to moodle. However, we could not keep it activated since it creates conflict with _Stack maths assesment_ , a custom question plugin.
To whoever it might interest, the plugin neutralize the mathjax render of latex equations that students types in the input box.

Thank you anyway for th ebeautifull plugin,
Balthazar.

**Comment by marinaglancy** [comment]
I hope this is resolved now in v1.2! Thanks for the report and help with reproduction!
