### ISSUE TITLE
Installed however not working.

### ISSUE THREAD

**Issue by VoytekBereza** [marinaglancy/moodle-tool_courserating#8]
Hey,

Sorry to be a complete newb but I just
1. Downloaded the zip file from the Moodle website.
2.  Admin > Plugins > Install Plugin - drag and dropped.

Looked at the site and there is no difference... am I missing something?

**Comment by VoytekBereza** [comment]
Scrap that, it is showing and tested; a fantastic plugin thank you soo much!

**Comment by marinaglancy** [comment]
Hi, sorry I missed this message. Ratings and reviews are displayed for the users who are logged in as guests
You can enable the setting
```
Auto-login guests
autologinguests
```

**Comment by marinaglancy** [comment]
When I was testing it I noticed that you already had to be logged in as guest before opening the course reviews popup and 'autologinguest' did not quite worked. In the version 1.5 that was just released non logged in users can also see course reviews
